# Generated by Django 4.1.3 on 2022-12-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_phone', to='account.phones', verbose_name='شماره تلفن'),
        ),
    ]
