# Generated by Django 4.1.3 on 2022-12-18 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveBigIntegerField(verbose_name='مسافت')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ حرکت')),
                ('finish_time', models.DateTimeField(verbose_name='تاریخ رسیدن')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=100)),
                ('req_start', models.DateTimeField(verbose_name='تاریخ شروع درخواست')),
                ('req_finish', models.DateTimeField(verbose_name='تاریخ پایان رسیدن')),
                ('start_loc', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مکان ثبت')),
                ('finish_loc', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مکان نهایی')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.driver', verbose_name='راننده')),
            ],
        ),
        migrations.CreateModel(
            name='RequestClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=100)),
                ('req_start', models.DateField(verbose_name='تاریخ شروع درخواست')),
                ('req_finish', models.DateField(verbose_name='تاریخ پایان رسیدن')),
                ('req_time_start', models.TimeField(verbose_name='تاریخ شروع درخواست')),
                ('req_time_finish', models.TimeField(verbose_name='تاریخ پایان رسیدن')),
                ('start_loc', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مکان ثبت')),
                ('finish_loc', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='مکان نهایی')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='رنگ')),
                ('model', models.DateTimeField(verbose_name='مدل')),
                ('number_plate_first_part', models.CharField(max_length=2, verbose_name='پلاک قسمت 1')),
                ('number_plate_second_part', models.CharField(max_length=1, verbose_name='پلاک قسمت 2')),
                ('number_plate_third_part', models.CharField(max_length=3, verbose_name='پلاک قسمت 3')),
                ('number_plate_forth_part', models.CharField(max_length=2, verbose_name='پلاک قسمت 4')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.driver', verbose_name='راننده')),
            ],
        ),
    ]
