# Generated by Django 4.1.3 on 2022-12-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestclient',
            name='req_finish',
        ),
        migrations.RemoveField(
            model_name='requestclient',
            name='req_time_finish',
        ),
        migrations.AlterField(
            model_name='requestclient',
            name='req_start',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ شروع درخواست'),
        ),
        migrations.AlterField(
            model_name='requestclient',
            name='req_time_start',
            field=models.TimeField(auto_now_add=True, verbose_name='تاریخ شروع درخواست'),
        ),
    ]
