# Generated by Django 4.1.3 on 2022-12-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_requestclient_req_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdriver',
            name='req_finish',
        ),
    ]
