# Generated by Django 4.1.3 on 2022-12-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_requestclient_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdriver',
            name='finish_loc',
        ),
    ]
