# Generated by Django 4.1.3 on 2022-12-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_driver_phone'),
        ('main', '0006_alter_requestdriver_req_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdriver',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.driver', verbose_name='راننده'),
        ),
    ]
