# Generated by Django 4.1.3 on 2022-12-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_requestdriver_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclient',
            name='distance',
            field=models.FloatField(default=0, verbose_name='مسافت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdriver',
            name='distance',
            field=models.FloatField(default=0, verbose_name='مسافت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(verbose_name='مسافت'),
        ),
    ]
