# Generated by Django 4.1.3 on 2022-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_requestclient_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdriver',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='مسافت'),
        ),
        migrations.AlterField(
            model_name='requestdriver',
            name='estimated_time',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='زمان تخمینی'),
        ),
    ]
