# Generated by Django 4.1.3 on 2022-12-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_requestdriver_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclient',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='مسافت'),
        ),
        migrations.AlterField(
            model_name='requestclient',
            name='estimated_time',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='زمان تخمینی'),
        ),
    ]
