# Generated by Django 4.1.3 on 2022-12-31 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_requestclient_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclient',
            name='finish_loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='مکان نهایی'),
        ),
    ]
