# Generated by Django 4.1.3 on 2022-12-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_driver_phone'),
        ('main', '0014_requestclient_finish_loc_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trip', to='account.driver', verbose_name='راننده'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trip', to='account.client', verbose_name='مسافر'),
        ),
    ]
