# Generated by Django 4.1.3 on 2022-12-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_requestclient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='req_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.requestdriver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='req_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.requestclient'),
        ),
    ]
