# Generated by Django 4.1.3 on 2022-12-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_requestclient_text_address_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclient',
            name='text_address_finish',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مقصد'),
        ),
        migrations.AlterField(
            model_name='requestclient',
            name='text_address_start',
            field=models.TextField(blank=True, null=True, verbose_name=' آدرس مبدا'),
        ),
    ]
